// <auto-generated />
using System;
using Books.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.API.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20260312110535_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Books.API.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            FirstName = "George",
                            LastName = "RR Martin"
                        },
                        new
                        {
                            Id = new Guid("c290f1ee-6c54-4b01-90e6-d701748f0852"),
                            FirstName = "Stephan",
                            LastName = "Fry"
                        },
                        new
                        {
                            Id = new Guid("b290f1ee-6c54-4b01-90e6-d701748f0853"),
                            FirstName = "JRR",
                            LastName = "Tolkien"
                        });
                });

            modelBuilder.Entity("Books.API.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e290f1ee-6c54-4b01-90e6-d701748f0851"),
                            AuthorId = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            Description = "First book in the A Song of Ice and Fire series.",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("f290f1ee-6c54-4b01-90e6-d701748f0852"),
                            AuthorId = new Guid("c290f1ee-6c54-4b01-90e6-d701748f0852"),
                            Description = "First book in The Kingkiller Chronicle series.",
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = new Guid("a290f1ee-6c54-4b01-90e6-d701748f0853"),
                            AuthorId = new Guid("b290f1ee-6c54-4b01-90e6-d701748f0853"),
                            Description = "Prequel to The Lord of the Rings.",
                            Title = "The Hobbit"
                        });
                });

            modelBuilder.Entity("Books.API.Entities.Book", b =>
                {
                    b.HasOne("Books.API.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
